server:
  port: 8080

spring:
  application:
    name: cloud-kitchen-backend
  datasource:
    url: jdbc:postgresql://10.0.5.247:5432/cloudkitchen
    username: postgres
    password: CloudKitchen2024!
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

app:
  cors:
    allowed-origins: "*"
